[workspace]
authors = ["Iason Krommydas <iason.krom@gmail.com>"]
channels = ["conda-forge"]
name = "coffea"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks.lab]
description = "Launch Jupyter Lab"
cmd = "jupyter lab"

[tasks.start]
depends-on = ["lab"]

[dependencies]
coffea = ">=2025.7.1,<2026"
dask = ">=2025.3.0,<2026"
distributed = ">=2025.3.0,<2026"
xrootd = ">=5.8.1,<6"
fsspec-xrootd = ">=0.5.1,<0.6"
jupyterlab = ">=4.4.5,<5"
notebook = ">=7.4.4,<8"
ipywidgets = ">=8.1.7,<9"
