[workspace]
authors = ["Iason Krommydas <iason.krom@gmail.com>"]
channels = ["conda-forge"]
name = "dask"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks.lab]
description = "Launch Jupyter Lab"
cmd = "dot -c && jupyter lab"

[tasks.start]
depends-on = ["lab"]

[dependencies]
coffea = ">=2025.7.2"
dask = ">=2025.3.0,<2026"
distributed = ">=2025.3.0,<2026"
mimesis = ">=18.0.0,<19"
jupyterlab = ">=4.4.5,<5"
notebook = ">=7.4.4,<8"
ipywidgets = ">=8.1.7,<9"
python-graphviz = ">=0.21,<0.22"
