[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "mplhep"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks.lab]
description = "Launch Jupyter Lab"
cmd = "jupyter lab"

[tasks.start]
depends-on = ["lab"]

[dependencies]
mplhep = ">=0.4.0,<0.5"
hist = ">=2.8.1,<3"
scikit-hep-testdata = ">=0.5.7,<0.6"
root = ">=6.34.4,<7"
uproot = ">=5.6.3,<6"
notebook = ">=7.4.4,<8"
jupyterlab = ">=4.4.4,<5"
ipywidgets = ">=8.1.7,<9"
