[workspace]
authors = ["Iason Krommydas <iason.krom@gmail.com>"]
channels = ["conda-forge"]
name = "columnar"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks.lab]
description = "Launch Jupyter Lab"
cmd = "jupyter lab"

[tasks.start]
depends-on = ["lab"]

[dependencies]
numpy = ">=2.3.1,<3"
awkward = ">=2.8.5,<3"
uproot = ">=5.6.3,<6"
vector = ">=1.6.3,<2"
hist = ">=2.8.1,<3"
matplotlib = ">=3.10.3,<4"
jupyterlab = ">=4.4.5,<5"
notebook = ">=7.4.4,<8"
ipywidgets = ">=8.1.7,<9"
